import React, { useState, useEffect, useCallback } from 'react';
import { API_BASE } from '../utils/api';

const BACKEND = API_BASE;

const STATUS_META = {
  Safe:          { color: 'var(--green-bright)',  bg: 'rgba(16,185,129,0.08)',  border: 'rgba(16,185,129,0.25)',  icon: '✅', label: 'Safe / Original' },
  Tampered:      { color: 'var(--red-bright)',    bg: 'rgba(239,68,68,0.08)',   border: 'rgba(239,68,68,0.25)',   icon: '⚠️', label: 'Tampered' },
  'AI-Generated':{ color: 'var(--amber-bright)', bg: 'rgba(245,158,11,0.08)',  border: 'rgba(245,158,11,0.25)', icon: '🤖', label: 'AI-Generated' },
};

const SEV_COLOR = { critical: 'var(--red-bright)', high: 'var(--amber-bright)', medium: 'var(--cyan)', low: 'var(--text-muted)' };

// ─── Helpers ───────────────────────────────────────────────────────────────────
function imgUrl(path) { return path ? `${BACKEND}/images/${path}` : null; }

function fmtDate(d) {
  return d ? new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
}

function trustColor(t) {
  if (t == null) return 'var(--text-muted)';
  return t >= 70 ? 'var(--green-bright)' : t >= 40 ? 'var(--amber-bright)' : 'var(--red-bright)';
}

/** Trigger a download of a remote URL as a named file */
async function downloadFile(url, filename) {
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
  } catch (_) { alert('Download failed — check the backend is running.'); }
}

/** Download a plain-text/JSON report generated client-side */
function downloadReport(c) {
  const lines = [
    '═══════════════════════════════════════════════════════',
    '         PHANTOMASHIELD — FORENSIC CASE REPORT         ',
    '═══════════════════════════════════════════════════════',
    '',
    `Case ID       : ${c.id}`,
    `File Name     : ${c.file_name}`,
    `Date          : ${fmtDate(c.date)}`,
    `Timestamp     : ${c.timestamp || '—'}`,
    '',
    '── VALIDATION ─────────────────────────────────────────',
    `Status        : ${c.status || '—'}`,
    `Label         : ${c.label  || '—'}`,
    `Trust Score   : ${c.trust_score != null ? c.trust_score + '%' : '—'}`,
    `Confidence    : ${c.confidence != null ? c.confidence + '%' : '—'}`,
    `Confidence Tier    : ${c.confidence_tier || '—'}`,
    `Clinical Reliability: ${c.clinical_reliability || '—'}`,
    `Requires Review    : ${c.requires_review != null ? String(c.requires_review) : '—'}`,
    '',
    '── RECOVERY ───────────────────────────────────────────',
    `Recovered     : ${c.recovered != null ? (c.recovered ? 'Yes' : 'No') : '—'}`,
    `Corruption Type: ${c.corruption_type || '—'}`,
    `Severity      : ${c.severity || '—'}`,
    `Affected %    : ${c.affected_pct != null ? c.affected_pct + '%' : '—'}`,
    `Quality Score : ${c.quality_score != null ? (c.quality_score * 100).toFixed(1) + '%' : '—'}`,
    '',
    '═══════════════════════════════════════════════════════',
    'Generated by PhantomaShield — Medical AI Platform',
    `Exported at: ${new Date().toISOString()}`,
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `PhantomaShield_Report_${c.id.slice(0, 8)}.txt`;
  a.click();
  URL.revokeObjectURL(a.href);
}

// ─── Cases hook ────────────────────────────────────────────────────────────────
function useCases(pollMs = 15000) {
  const [cases, setCases] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    const fetch_ = async () => {
      try {
        const res = await fetch(`${BACKEND}/cases?limit=200`);
        if (!res.ok) return;
        const data = await res.json();
        if (!cancelled) { setCases(data.cases || []); setTotal(data.total || 0); }
      } catch (_) { /* offline */ } finally {
        if (!cancelled) setLoading(false);
      }
    };
    fetch_();
    const t = setInterval(fetch_, pollMs);
    return () => { cancelled = true; clearInterval(t); };
  }, [pollMs]);

  return { cases, total, loading };
}

// ─── Case Card ─────────────────────────────────────────────────────────────────
function CaseCard({ c, onClick }) {
  const sm = STATUS_META[c.status] || { color: 'var(--text-muted)', bg: 'rgba(255,255,255,0.04)', border: 'rgba(255,255,255,0.1)', icon: '🩻' };
  const src = imgUrl(c.image_path);
  const date = fmtDate(c.date);

  return (
    <article
      className="case-card glass-panel case-card-clickable"
      id={`archive-case-${c.id}`}
      role="button"
      tabIndex={0}
      aria-label={`View report for ${c.file_name}`}
      onClick={() => onClick(c)}
      onKeyDown={e => (e.key === 'Enter' || e.key === ' ') && onClick(c)}
    >
      <div className="case-card-image">
        {src
          ? <img src={src} alt={`Preview of ${c.file_name}`} loading="lazy" />
          : <div className="case-card-image-placeholder" aria-hidden="true">🩻</div>
        }
        {/* Hover overlay */}
        <div className="case-card-hover-overlay" aria-hidden="true">
          <span className="case-card-hover-label">View Report</span>
        </div>
        <div className="case-card-badges">
          {c.has_validation && <span className="case-badge validate-badge" title="Validated">V</span>}
          {c.has_recovery   && <span className="case-badge recover-badge"  title="Recovered">R</span>}
        </div>
      </div>

      <div className="case-card-body">
        <div className="case-card-filename" title={c.file_name}>{c.file_name}</div>
        {c.status && (
          <div className="case-card-status" style={{ color: sm.color, background: sm.bg, borderColor: sm.border }}>
            <span>{sm.icon}</span><span>{c.status}</span>
          </div>
        )}
        <div className="case-card-metrics">
          {c.trust_score != null && (
            <div className="case-metric">
              <span className="case-metric-label">Trust</span>
              <span className="case-metric-value" style={{ color: trustColor(c.trust_score) }}>{c.trust_score}%</span>
            </div>
          )}
          {c.quality_score != null && (
            <div className="case-metric">
              <span className="case-metric-label">Quality</span>
              <span className="case-metric-value" style={{ color: 'var(--purple-light)' }}>{(c.quality_score * 100).toFixed(1)}%</span>
            </div>
          )}
          {c.recovered != null && (
            <div className="case-metric">
              <span className="case-metric-label">Recovered</span>
              <span className="case-metric-value" style={{ color: c.recovered ? 'var(--green-bright)' : 'var(--red-bright)' }}>
                {c.recovered ? '✓' : '✗'}
              </span>
            </div>
          )}
        </div>
        <div className="case-card-footer">
          <span className="case-card-date">📅 {date}</span>
          {c.severity && (
            <span className="case-card-severity" style={{ color: SEV_COLOR[c.severity] || 'var(--text-muted)' }}>{c.severity}</span>
          )}
        </div>
      </div>
    </article>
  );
}

// ─── Case Detail Modal ─────────────────────────────────────────────────────────
function CaseDetailModal({ c, onClose }) {
  const [imgTab, setImgTab] = useState('original'); // original | heatmap | corrupted | recovered
  const sm = STATUS_META[c.status] || { color: 'var(--text-muted)', bg: 'rgba(255,255,255,0.04)', border: 'rgba(255,255,255,0.1)', icon: '🩻', label: c.status };

  // Close on Escape
  useEffect(() => {
    const handler = e => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  // Image options
  const imgOptions = [];
  if (c.image_path)           imgOptions.push({ key: 'original',  label: 'Original',  url: imgUrl(c.image_path) });
  if (c.heatmap_path)         imgOptions.push({ key: 'heatmap',   label: 'Heatmap',   url: imgUrl(c.heatmap_path) });
  if (c.image_path && c.has_recovery) imgOptions.push({ key: 'corrupted', label: 'Corrupted', url: imgUrl(c.image_path) });
  if (c.recovered_image_path) imgOptions.push({ key: 'recovered', label: 'Recovered', url: imgUrl(c.recovered_image_path) });

  const activeImgUrl = imgOptions.find(o => o.key === imgTab)?.url || imgOptions[0]?.url;

  // Auto-select first available tab
  useEffect(() => { if (imgOptions.length) setImgTab(imgOptions[0].key); }, [c.id]);

  const date = fmtDate(c.date);

  return (
    <div className="modal-overlay" role="dialog" aria-modal="true" aria-label={`Case report: ${c.file_name}`} onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="modal-panel">

        {/* ── Modal Header ── */}
        <div className="modal-header">
          <div className="modal-header-left">
            <div className="modal-header-icon" aria-hidden="true">🩻</div>
            <div>
              <div className="modal-filename">{c.file_name}</div>
              <div className="modal-meta">Case ID: <span className="mono">{c.id.slice(0, 12)}…</span> · {date}</div>
            </div>
          </div>
          <button className="modal-close-btn" onClick={onClose} aria-label="Close modal" id="modal-close-btn">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
              <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
            </svg>
          </button>
        </div>

        {/* ── Modal Body ── */}
        <div className="modal-body">

          {/* LEFT: Image viewer */}
          <div className="modal-image-col">
            <div className="modal-image-tabs">
              {imgOptions.map(opt => (
                <button
                  key={opt.key}
                  className={`modal-img-tab${imgTab === opt.key ? ' active' : ''}`}
                  onClick={() => setImgTab(opt.key)}
                >
                  {opt.label}
                </button>
              ))}
            </div>
            <div className="modal-image-frame">
              {activeImgUrl
                ? <img src={activeImgUrl} alt={imgTab} className="modal-image" />
                : <div className="modal-image-empty">No image available</div>
              }
            </div>
            {/* Image download */}
            {activeImgUrl && (
              <button
                className="modal-dl-btn secondary"
                onClick={() => downloadFile(activeImgUrl, `${c.file_name.replace('.dcm','')}_${imgTab}.png`)}
              >
                <DownloadIcon /> Download {imgTab.charAt(0).toUpperCase() + imgTab.slice(1)} Image
              </button>
            )}
          </div>

          {/* RIGHT: Report */}
          <div className="modal-report-col">

            {/* Status */}
            {c.status && (
              <div className="modal-section">
                <div className="modal-section-label">Forensic Verdict</div>
                <div className="modal-status-badge" style={{ color: sm.color, background: sm.bg, borderColor: sm.border }}>
                  {sm.icon} {sm.label || c.status}
                </div>
              </div>
            )}

            {/* Validation metrics */}
            {c.has_validation && (
              <div className="modal-section">
                <div className="modal-section-label">Validation Analysis</div>
                <div className="modal-metric-grid">
                  <MetricRow label="Trust Score" value={`${c.trust_score}%`} color={trustColor(c.trust_score)} />
                  <MetricRow label="Confidence" value={`${c.confidence}%`} color="var(--cyan)" />
                  {c.confidence_tier && <MetricRow label="Confidence Tier" value={c.confidence_tier} />}
                  {c.clinical_reliability && <MetricRow label="Clinical Reliability" value={c.clinical_reliability} />}
                  {c.requires_review != null && (
                    <MetricRow
                      label="Requires Review"
                      value={c.requires_review ? 'Yes' : 'No'}
                      color={c.requires_review ? 'var(--amber-bright)' : 'var(--green-bright)'}
                    />
                  )}
                </div>
                {/* Trust progress bar */}
                {c.trust_score != null && (
                  <div className="modal-progress-wrap">
                    <div className="modal-progress-track">
                      <div
                        className="modal-progress-fill"
                        style={{ width: `${c.trust_score}%`, background: `linear-gradient(90deg, ${trustColor(c.trust_score)}66, ${trustColor(c.trust_score)})` }}
                      />
                    </div>
                    <span className="modal-progress-label">{c.trust_score}% Trust</span>
                  </div>
                )}
              </div>
            )}

            {/* Recovery metrics */}
            {c.has_recovery && (
              <div className="modal-section">
                <div className="modal-section-label">Recovery Analysis</div>
                <div className="modal-metric-grid">
                  <MetricRow
                    label="Recovered"
                    value={c.recovered ? 'Yes ✓' : 'No ✗'}
                    color={c.recovered ? 'var(--green-bright)' : 'var(--red-bright)'}
                  />
                  {c.corruption_type && <MetricRow label="Corruption Type" value={c.corruption_type} />}
                  {c.severity && (
                    <MetricRow label="Severity" value={c.severity.toUpperCase()} color={SEV_COLOR[c.severity]} />
                  )}
                  {c.affected_pct != null && <MetricRow label="Affected Region" value={`${c.affected_pct}%`} color="var(--amber-bright)" />}
                  {c.quality_score != null && (
                    <MetricRow label="Recovery Quality" value={`${(c.quality_score * 100).toFixed(1)}%`} color="var(--purple-light)" />
                  )}
                </div>
              </div>
            )}

            {/* Download actions */}
            <div className="modal-section modal-actions">
              <div className="modal-section-label">Downloads</div>
              <div className="modal-dl-group">
                <button className="modal-dl-btn primary" onClick={() => downloadReport(c)} id="modal-dl-report">
                  <DownloadIcon /> Download Report (.txt)
                </button>
                {c.recovered_image_path && (
                  <button
                    className="modal-dl-btn purple"
                    onClick={() => downloadFile(imgUrl(c.recovered_image_path), `${c.file_name.replace('.dcm', '')}_recovered.png`)}
                    id="modal-dl-recovered"
                  >
                    <DownloadIcon /> Download Recovered Image
                  </button>
                )}
                {c.heatmap_path && (
                  <button
                    className="modal-dl-btn amber"
                    onClick={() => downloadFile(imgUrl(c.heatmap_path), `${c.file_name.replace('.dcm', '')}_heatmap.png`)}
                    id="modal-dl-heatmap"
                  >
                    <DownloadIcon /> Download Heatmap
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Tiny helpers ──────────────────────────────────────────────────────────────
function MetricRow({ label, value, color }) {
  return (
    <div className="modal-metric-row">
      <span className="modal-metric-label">{label}</span>
      <span className="modal-metric-value" style={color ? { color } : {}}>{value ?? '—'}</span>
    </div>
  );
}

function DownloadIcon() {
  return (
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
      <polyline points="7 10 12 15 17 10"/>
      <line x1="12" y1="15" x2="12" y2="3"/>
    </svg>
  );
}

// ─── Case Archive Page ─────────────────────────────────────────────────────────
export default function CaseArchive() {
  const { cases, total, loading } = useCases();
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState(null);

  const openCase = useCallback(c => setSelected(c), []);
  const closeCase = useCallback(() => setSelected(null), []);

  const filtered = cases.filter(c => {
    const matchModule =
      filter === 'validation' ? c.has_validation :
      filter === 'recovery'   ? c.has_recovery   : true;
    const matchSearch = search.trim() === '' ||
      c.file_name.toLowerCase().includes(search.trim().toLowerCase());
    return matchModule && matchSearch;
  });

  return (
    <div className="archive-page" id="archive-view">
      {/* Page header */}
      <header className="archive-header">
        <div className="archive-header-left">
          <div className="archive-icon-wrap" aria-hidden="true">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 7V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2"/>
              <line x1="12" y1="12" x2="12" y2="16"/><line x1="10" y1="14" x2="14" y2="14"/>
            </svg>
          </div>
          <div>
            <h1 className="archive-title">
              Case Archive
              {total > 0 && <span className="cases-count-badge">{total}</span>}
            </h1>
            <p className="archive-sub">Click any card to view the full forensic report &amp; download files</p>
          </div>
        </div>

        <div className="archive-controls">
          <div className="archive-search-wrap">
            <svg className="archive-search-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
              <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
            </svg>
            <input
              className="archive-search"
              type="search"
              placeholder="Search by filename…"
              value={search}
              onChange={e => setSearch(e.target.value)}
              aria-label="Search cases by filename"
              id="archive-search-input"
            />
          </div>
          <div className="cases-filter-tabs" role="tablist" aria-label="Filter cases by module">
            {[
              { key: 'all',        label: 'All Cases'  },
              { key: 'validation', label: 'Validation' },
              { key: 'recovery',   label: 'Recovery'   },
            ].map(tab => (
              <button key={tab.key} role="tab" aria-selected={filter === tab.key}
                className={`cases-tab${filter === tab.key ? ' active' : ''}`}
                id={`archive-tab-${tab.key}`} onClick={() => setFilter(tab.key)}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>
      </header>

      {/* Body */}
      {loading && <div className="cases-empty"><span className="cases-empty-icon">⏳</span><span>Loading cases…</span></div>}

      {!loading && filtered.length === 0 && (
        <div className="cases-empty">
          <span className="cases-empty-icon">{search ? '🔍' : '📂'}</span>
          <span>{search ? `No cases match "${search}".` : 'No cases found. Run a forensic detection or recovery to populate this archive.'}</span>
        </div>
      )}

      {!loading && filtered.length > 0 && (
        <div className="cases-grid archive-grid" role="list">
          {filtered.map((c, i) => (
            <div key={c.id} role="listitem" style={{ animationDelay: `${i * 0.04}s` }}>
              <CaseCard c={c} onClick={openCase} />
            </div>
          ))}
        </div>
      )}

      {/* Detail Modal */}
      {selected && <CaseDetailModal c={selected} onClose={closeCase} />}
    </div>
  );
}
